version: '3.8'

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    image: "j3s5e/ttt-client:latest"
    volumes:
      - /app/node_modules
      - ./client:/app

  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
    image: "j3s5e/ttt-server:latest"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "${SOCKET_PORT}:4242"
    environment:
      - EXT_SOCKET_PORT=${SOCKET_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - WEB_CLIENT_URL=${WEB_CLIENT_URL}

  nginx:
    image: nginx
    volumes:
      - ./nginx-conf.d:/etc/nginx/nginx.conf
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - client
      - server