version: '3.8'

services:
  client:
    image: "j3s5e/ttt-client:latest"

  server:
    image: "j3s5e/ttt-server:latest"
    ports:
      - "4243:4242"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx
    volumes:
      - ./nginx-conf.d:/etc/nginx/nginx.conf
    ports:
      - "81:80"
    depends_on:
      - client
      - server